//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.25 at 02:43:30 PM SAST 
//


package rca.soap.oreste.suppliers;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rca.soap.oreste.suppliers package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rca.soap.oreste.suppliers
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateSupplierDetailsRequest }
     * 
     */
    public UpdateSupplierDetailsRequest createUpdateSupplierDetailsRequest() {
        return new UpdateSupplierDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteSupplierDetailsResponse }
     * 
     */
    public DeleteSupplierDetailsResponse createDeleteSupplierDetailsResponse() {
        return new DeleteSupplierDetailsResponse();
    }

    /**
     * Create an instance of {@link UpdateSupplierDetailsResponse }
     * 
     */
    public UpdateSupplierDetailsResponse createUpdateSupplierDetailsResponse() {
        return new UpdateSupplierDetailsResponse();
    }

    /**
     * Create an instance of {@link GetAllSupplierDetailsResponse }
     * 
     */
    public GetAllSupplierDetailsResponse createGetAllSupplierDetailsResponse() {
        return new GetAllSupplierDetailsResponse();
    }

    /**
     * Create an instance of {@link CreateSupplierDetailsResponse }
     * 
     */
    public CreateSupplierDetailsResponse createCreateSupplierDetailsResponse() {
        return new CreateSupplierDetailsResponse();
    }

    /**
     * Create an instance of {@link CreateSupplierDetailsRequest }
     * 
     */
    public CreateSupplierDetailsRequest createCreateSupplierDetailsRequest() {
        return new CreateSupplierDetailsRequest();
    }

    /**
     * Create an instance of {@link GetSupplierDetailsRequest }
     * 
     */
    public GetSupplierDetailsRequest createGetSupplierDetailsRequest() {
        return new GetSupplierDetailsRequest();
    }

    /**
     * Create an instance of {@link SupplierDetails }
     * 
     */
    public SupplierDetails createSupplierDetails() {
        return new SupplierDetails();
    }

    /**
     * Create an instance of {@link GetAllSupplierDetailsRequest }
     * 
     */
    public GetAllSupplierDetailsRequest createGetAllSupplierDetailsRequest() {
        return new GetAllSupplierDetailsRequest();
    }

    /**
     * Create an instance of {@link GetSupplierDetailsResponse }
     * 
     */
    public GetSupplierDetailsResponse createGetSupplierDetailsResponse() {
        return new GetSupplierDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteSupplierDetailsRequest }
     * 
     */
    public DeleteSupplierDetailsRequest createDeleteSupplierDetailsRequest() {
        return new DeleteSupplierDetailsRequest();
    }

}
