//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.25 at 03:37:17 PM SAST 
//


package rca.soap.oreste.suppliers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="supplierDetails" type="{http://soap.rca/oreste/suppliers}SupplierDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "supplierDetails"
})
@XmlRootElement(name = "UpdateSupplierDetailsRequest")
public class UpdateSupplierDetailsRequest {

    @XmlElement(required = true)
    protected SupplierDetails supplierDetails;

    /**
     * Gets the value of the supplierDetails property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierDetails }
     *     
     */
    public SupplierDetails getSupplierDetails() {
        return supplierDetails;
    }

    /**
     * Sets the value of the supplierDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierDetails }
     *     
     */
    public void setSupplierDetails(SupplierDetails value) {
        this.supplierDetails = value;
    }

}
